---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver_config:
      provision_command: apt-get install net-tools

suites:
  - name: master
    run_list:
      - recipe[optoro_redis]
    attributes: {
      redisio: {
        servers: [
          { name: "Master", port: 6379 }
        ]
      }
    }
  - name: replication-client
    run_list:
      - recipe[optoro_redis]
    attributes: {
      redisio: {
        servers: [
          { name: "Master", port: 6379 },
          {
            name: "Slave1",
            port: "6380",
            slaveof: { address: "127.0.0.1", port: 6379 }
          }
        ]
      }
    }
