---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 12.6.0
  customize:
    natdnshostresolver1: "on"
    memory: 2048
provisioner: chef_zero

platforms:
- name: ubuntu-14.04
  driver_config:
    box: opscode_ubuntu-14.04_chef-provisionerless
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box

suites:
  - name: master
    run_list:
      - recipe[optoro_redis::test]
      - recipe[optoro_redis]
    attributes:
      redisio:
        servers:
          - port: 6379
  - name: replication-client
    run_list:
      - recipe[optoro_redis::test]
      - recipe[optoro_redis]
    attributes:
      redisio:
        servers:
          - port: 6379
          - port: 6380
            slaveof:
              address: 127.0.0.1
              port: 6379
